### ISSUE TITLE
dlgList not showing nativeGUI, always falls back to TextCli

### ISSUE THREAD

**Issue by virscience001** [SciViews/svDialogs#1]
selection<-dlgList(c(1,2,3,4,5), multiple = TRUE, title = "Select variables",gui = .GUI)$res

this does not work in Mac OS High sierra on Macbook pro 2018 model. This used to work in my older Mac which was upgraded from EI Capitan OS. Other dialog boxes are working fine though like dlg_message and dlg_input

I have installed xquartz from https://www.xquartz.org/ as mentioned on CRAN site.

**Comment by phgrosjean** [comment]
I just tried on my side, same config, but using R 3.4.4 without bugs. I have not installed R 3.5.0 on this Mac yet. Which R version do you use?
Did you tried this with Rapp, R in a terminal, or in RStudio?

**Comment by virscience001** [comment]
I tried on Rstudio latest with R 3.5

**Comment by phgrosjean** [comment]
Ah OK! So, please, read the note in ?dlgList. RStudio does not have a list selection dialog box yet! So, as the general mechanism, when svDialogs cannot display a graphical dialog box, it falls back to a text version at the R Console. So, correct behavior. Closes issue #1.
