### ISSUE TITLE
dlg_dir char encoding

### ISSUE THREAD

**Issue by GuyMarty-ARSOC** [SciViews/svDialogs#4]
Bonjour,
Windows 7, RStudio 1.2.1335, R 3.6.0

Je ne sais pas si cela vient de svDialogs, R or Rstudio, quand je sélectionne un répertoire dont le nom de chemin contient un caractère avec diacritique ('à' par exemple) ce caractère est mal encodé et l'utilisation de cette chaîne de caractère entraîne des erreurs.

In poor English :
I known if it's come from svDialogs, R or Rstudio : if I select a directory using dlg_gui which path name contains a character with diacritic (as 'à') this char is wrongly encoded thus this path raises an error when I use it in other function.

I hope this will be usefull

En espérant que cela sera utile.
Salutations
GM

**Comment by GuyMarty-ARSOC** [comment]
```dlg_dir(title = "Choisissez le répertoire de sauvegarde des téléchargements")$res```
Même l'affichage n'est pas bon (voir copie d'écran)
Even the display of title is wrong (see screenshot)

**Comment by GuyMarty-ARSOC** [comment]
```dlg_dir(title = "Choisissez le répertoire de sauvegarde des téléchargements")$res```
Même l'affichage de title n'est pas bon 
Even the display of title is wrong

**Comment by GuyMarty-ARSOC** [comment]
Après moult recherches la seule réponse que j'ai euest  : la gestion de l'encodage dans R, R Studio sous Windows, c'est un enfer. Il ne pourra pas être résolu au niveau de svDialogs. Si vous avez une astuce, je suis preneur.

After a lot searches, the answer I get is : R, RStudio on Windows is a character encoding hell. It can't be solved in svDialogs. But, if you have au workaround, it would be great.

**Comment by phgrosjean** [comment]
Yes, encoding is a nightmare. It is somehow solved in R itself, particularly in Linux and MacOS where you can use UTF-8. In Windows, it is a different story, but solutions exist... for most cases. Apparently, your configuration is not one of these. You can test different string encodings in R before passing the string to the dialog function, and then, reencoding the answer. If you find a solution, please, send a pull request. Thanks.
